### ISSUE TITLE
Simple editor/composer

### ISSUE THREAD

**Issue by smalls** [google/model-viewer#12]
We've been calling this a composer, but we need a simple way to at least:

- [ ] Import multiple models, and export as a single model
- [ ] Perform simple movements (changing the origin, scaling)
- [ ] Preview how the model will appear embedded or in AR

**Comment by elalish** [comment]
Done!
