### ISSUE TITLE
modelviewer.dev examples and docs

### ISSUE THREAD

**Issue by chrismgeorge** [google/model-viewer#1563]
### Description
Redesigning modelviewer.dev examples and docs
(difficulty / 5)

https://github.com/google/model-viewer/pulls?q=+is%3Apr+author%3A%40me+

### Todos
- [ ] optimize sidebar (4/5)
- [ ] move lighthouse examples over and link to them from docs (3/5)
- [x] documentation: fill in data in json file (3/5)
- [x] examples: fill in json data (3/5)
- [x] move categories to folders, modify sidebar for examples (3/5)
- [x] examples, example specific reference (links, automatically jump to on page load) (2/5)
- [x] examples: sidebar needs to update with scroll (2/5) 
- [x] linking -- add URI update that pushes screen to href after JSON loads (1/5)
- [x] sidebar toggle (2/5) 
- [x] hide subcategory when category not in view (2/5)
- [x] fix method names in sidebar (2/5)
- [x] add all of the links to the docs (2/5)
- [ ] add black opacity behind open sidebar on mobile (2/5)
- [x] small stuff: sidebar close on click on mobile (1/5)
- [x] final UI adjustments

### Bugs
- [x] another clicking on sidebar bug (2/5)
- [x] fix Click on methods, events, methods, sidebar messes up (3/5) **This has to do with the algorithm for selecting and updating. I.e. when a click doesn't remove whats in view. Need to reset on click.** 
- [x] figure out why Animations isn't displaying properly on deploy. **This has to do with the fact that animation.html is in examples already. Once it is removed, then it will default to examples/animation/index.html**

### Mobile Friendly
- [x] Make Docs Mobile Friendly (3/5) 
- [x] Make Examples Mobile Friendly, add examples header toggle, and CSS (2/5) 
- [x] Clean up (1/5)

### Front Page
- [x] Modify front page design to match Figma (3/5)
