### ISSUE TITLE
Model Editor bug/feature list

### ISSUE THREAD

**Issue by chrismgeorge** [google/model-viewer#1614]
### Bugs
- [x] expandable content 
- [x] camera doesn't use modelviewer's camera --> multiple bugs associated including poster update, i.e. window resizing/ autorotate are causing poster to not match up with actual image
- [x] broken testing

### Todos
- [x] Get Redux debugging tools setup to streamline bugs
- [x] Cost/benefit analysis if it is worthwhile chucking everything out, and restarting with a more featurefull framework, like Angular or React
