### ISSUE TITLE
Optimizing environment map generation

### ISSUE THREAD

**Issue by cdata** [google/model-viewer#347]
This issue tracks the various other issues related to optimizing environment map generation

- [x] #336 Cache environment map
- [ ] #341 Generate PMREM ahead of time
- [ ] #342 Generate PMREM off main thread
- [x] #343 Lazily generate PMREM
- [x] #344 Don't generate maps more than necessary
- [x] #346 Pick a better name for `experimental-pmrem`
